server:
  port: 10010

spring:
  application:
    name: mars-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #eureka 注册显示 ip:端口号
hystrix:
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
ribbon:
  ConnectTimeout: 30000 # ribbon链接超时时长
  ReadTimeout: 600000 # ribbon读取超时时长
  MaxAutoRetries: 10  # 当前服务重试次数
  MaxAutoRetriesNextServer: 1 # 切换服务重试次数
  OkToRetryOnAllOperations: true # 是否对所有的请求方式都重试，只对get请求重试
  eureka:
    enabled: true
  okhttp:
    enabled: true
#  listOfServers: localhost:8080
zuul:
  prefix: /mars
  sensitive-headers:
  routes:
    mars-website-info: /websiteinfo/**
    mars-users: /users/**
  host:
    max-per-route-connections: 100000
    max-total-connections: 100000
    connect-timeout-millis: 300000
    socket-timeout-millis: 300000
  servlet-path: /zuul
