server:
  port: 8002
spring:
  main:
    allow-bean-definition-overriding: false
#  datasource:
#    username: root
#    password: 1234
#    url: jdbc:mysql://localhost:3306/mars_user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: mars-website-info
#  servlet:
#    multipart:
#      enabled: true
#      maxRequestSize: 2000MB
#      maxFileSize: 2000MB
#      resolve-lazily: false
##  redis:
##    host: 192.168.0.141
##    port: 6379
##    password:
#mybatis:
#  typeAliasesPackage: com.mars.userservice
#  mapperLocations: classpath:mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: true
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
ribbon:
  eureka:
    enabled: true
#feign:
#  httpclient:
#    enabled: true
#    connection-timeout: 6000000
#  okhttp:
#    enabled: true
#  hystrix:
#    enabled: false
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 30000
#zuul:
#  debug:
#    request: true
